version: '3.7'

services:
  whizart-mongo:
    env_file:
      - .env.dev
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    volumes:
      - whizart_db_data:/data/db
    ports:
      - 27017:27017
volumes:
  whizart_db_data:
